#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d a b c d e f g h
bspc monitor -d I II III IV V VI VII VIII

bspc config border_width         1
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled

export TERMINAL=ghostty
export BROWSER=brave
killall plank -9
exec ~/.config/polybar/launch.sh &
feh --bg-scale ~/.config/bspwm/wallpaper.jpg &
picom &
emacs --daemon &
xset +fp /home/eduardo/.local/share/fonts &
xset fp rehash &
setxkbmap -layout latam &
xsetroot -cursor_name left_ptr &
udiskie &
mpd & 
mpDris2 &
